#!/bin/sh
# $OpenBSD: Xsetup_0.in,v 1.1 2021/08/30 15:38:27 matthieu Exp $

prefix="/usr/X11R6"
exec_prefix="${prefix}"

#${exec_prefix}/bin/xrandr -s 1280x800

${exec_prefix}/bin/xsetroot -solid "#333340"
